name: TARSIS
configurations:
  values:
  - 866d074e-bc03-49a6-941a-11ebc1b3f136
  default: 866d074e-bc03-49a6-941a-11ebc1b3f136
modes:
- name: Success
  summary: A mode where the recipe successes
  description: A mode where the recipe successes, used for testing
  key: TarsisSuccess
  tagger: null
  rawimage: IMAGE_TEST
- name: Fail
  summary: A mode where the recipe fails
  description: A mode where the recipe fails, used for testing
  key: TarsisFail
  tagger: null
  rawimage: IMAGE_TEST
pipelines:
  default:
    version: 1
    recipes:
      TarsisSuccess: numina.core.utils.AlwaysSuccessRecipe
      TarsisFail: numina.core.utils.AlwaysFailRecipe 
